### ISSUE TITLE
when i kill app then react-native-android-notification-listener not listen any notification also when i reopen my appication, react-native-android-notification-listener not listen new notification 🐛 [BUG]

### ISSUE THREAD

**Issue by Aakashsajjad095** [leandrosimoes/react-native-android-notification-listener#16]
when i kill app then react-native-android-notification-listener not listen any notification also when i reopen my appication, react-native-android-notification-listener not listen new notification

**Comment by leandrosimoes** [comment]
Hi @Aakashsajjad095 ... could you please open this issue again but following the issue template. There's a reason for this, and the reason is to understand better the problem through all the information that is presented in the template. I'll close this issue so you can open a new one. Also, there's no reason for the title of the issue to be this big. Just put some simple introduction in the issues titles.
