### ISSUE TITLE
notification listener stop after sometime

### ISSUE THREAD

**Issue by zoobibackups** [leandrosimoes/react-native-android-notification-listener#24]
for the first time when the app is installed is listening to notifications. but after some time may be an hour or a day the notification listener service is stoped. the library working fine on the android simulators but on real devices like **Xiaomi mi** **android 10 and android 11** there is an issue. if I restart the device or clear app data then it starts working again.

**To Reproduce**
 [run this sample ](https://github.com/leandrosimoes/react-native-android-notification-listener/tree/master/sample)

**Expected behavior**
must listen notifications 
**Library version:**
 -  `"react-native-android-notification-listener": "^2.0.0",`

**Smartphone**
 - Device: Xiaomi 
 - OS:  Android 10 android 11

**Additional context**
I have debugged this on android studio and put logs there but i was unable to here a simple notification.

**Comment by leandrosimoes** [comment]
Hi @zoobibackups ! Thanks for open this issue.

This library is currently at version [3.1.2](https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v3.1.2) and you are using the 2.0.0 version. 
This problem was fixed in version [3.0.0](https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v3.0.0) so you have to update your library to the last version.
Be aware that there are some breaking changes on the way you use the library since version 3.0.0, so follow [these](https://github.com/leandrosimoes/react-native-android-notification-listener/tree/v3.1.2#usage) instructions to setup you project correctly.

Thanks!
