### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by aditya27dev** [leandrosimoes/react-native-android-notification-listener#27]
I was checking reports from google crashes and ANR so I found my app is crashing because of this issue.

```Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8a0af1e u0 com.streamalerts/com.lesimoes.androidnotificationlistener.RNAndroidNotificationListener}```

Can you explain me why my app is crashing with this and what will be the solution?

![image](https://user-images.githubusercontent.com/25629063/132131268-3a3adeb7-67b4-45c8-ac92-aa0df41bd677.png)

**Comment by leandrosimoes** [comment]
Hi @aditya27dev.

No, I cannot say why your app is crashing, and also I cannot say what will be the solution since I don't have any information about the problem besides the error message.
There's a reason that we put some issue templates here, for example, to get enough information about the error so we can understand what is happening.
So I'm closing this issue right now, but you can feel free to open a new issue using [this Bug Report Template](https://github.com/leandrosimoes/react-native-android-notification-listener/issues/new?assignees=&labels=bug&template=bug_report.md&title=%F0%9F%90%9B+%5BBUG%5D+ENTER_YOUR_TITLE_HERE) and DON'T FORGET to read everything in the template and fill all the information needed.

Thanks.

**Comment by tommyt4a** [comment]
have you solved the issue?
