### ISSUE TITLE
Not Being able to get notifications

### ISSUE THREAD

**Issue by PaoloGuimalan** [leandrosimoes/react-native-android-notification-listener#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It works when I install a debug and release apk in Nox Player where it has Android 7.1.0 but not in my Phone. It says that it is already authorized in reading the notifications but somehow doesn't really do anything. There are also no errors prompting.

### Library version that you are testing

5.0.0

### Device

Oppo A5s

### Android Version

8.1.0

**Comment by PaoloGuimalan** [comment]
**Update**: It is now working, turns out to be that I have to turn off (not restart) and on again my phone after I allow permission on the app. I do not know why it works like that but it works.

**Comment by leandrosimoes** [comment]
Hi @PaoloGuimalan, I'm glad that worked.

I have been trying to find out why this is happening but with no success at all. I know that old versions of Android and some device particularities have issues with headless services, but I can't ensure that this is the problem here. I can't figure out when this is the case since the devices that I'm able to test just work as expected. In this case, I would just need help from those that have the same device because even with emulators I think it is not the same as testing in the real devices. 
With this in mind, I'll add this as a known issue in the documentation for everyone to be aware of.

Thanks again for you help on this.
